DELETE FROM `Participants`;
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Barry','Vincent','vbarry@gmail.com',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Beaudoin','Francis','ledome27@gmail.com',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Bellavance','Louis','louis.bellavance@intact.net',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Bouchard','Mario','mario.bouchard@me.com',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Chau','Fred','frederic.chau@intact.net',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Deslandes','Pierre','pierre.deslandes@intact.net',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Gagnon','Guy','guygag@gmail.com',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Huppé','Sylvain','sylvain@3csh.ca',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Jutras','André','ajjutras@gmail.com',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Lefebvre','Yvon','yvon.lefebvre@intact.net',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Legault','Jacques','jacques.legault@desjardins.com',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Mainville','Fred','frederick.mainville@scd.desjardins.com',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Morin','Benoît','ben.morin@videotron.ca',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Parent','André','aparent@lcci.qc.ca',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Piette','Luc','lpiette@groupeedc.com',NULL);
INSERT INTO `Participants`(`nom`, `prenom`, `courriel`, `telephone`) VALUES ('Roy','Guy','guy_sixpack@yahoo.fr',NULL);